#!/usr/bin/env python3
"""Make a VMD movie and arrows for one PCA / normal-mode motion vector.

Two files are written:
  PREFIX.pdb         multi-model PDB, x(k) = x_ref + A * sin(2*pi*k/N) * s * v
  PREFIX_arrows.tcl  Tcl script drawing one arrow per atom (x_ref -> x_ref + A * v)

where v is the mode vector (3N values), A the amplitude in Angstrom, and s
(= +1, or -1 with --flip) the sign; the sign of a mode vector is arbitrary.

The mode vector can be given as
  --vector FILE           plain text, 3N values in one column (x1 y1 z1 x2 ...)
                          or N rows of "x y z"; lines starting with '#' ignored
  --evecs FILE --mode K   cpptraj eigenvector file (output of 'diagmatrix',
                          used for both PCA and quasi-harmonic/normal modes)

With --evecs, the average structure stored in the file is fitted onto the
reference PDB and the vector is rotated into the PDB frame (disable with
--no-fit). This matters when the PDB is not in the frame the covariance matrix
was computed in, e.g. after aligning on a subset of residues. The eigenvalue
is also read, so the amplitude can be given as --nsigma (PCA: sigma =
sqrt(eigenvalue) in Angstrom). Otherwise give --amp in Angstrom.

The reference PDB must contain the atoms of the vector in the same order.
If the PDB has more atoms (e.g. all-atom PDB with a CA-only vector), select
the matching ones with --atom-names, e.g. --atom-names CA.
"""
import argparse
import os
import re
import sys

import numpy as np


def read_pdb(path, atom_names=None):
    lines = []
    for l in open(path):
        if not l.startswith(("ATOM", "HETATM")):
            continue
        if atom_names and l[12:16].strip() not in atom_names:
            continue
        lines.append(l.rstrip("\n"))
    xyz = np.array([[float(l[30:38]), float(l[38:46]), float(l[46:54])] for l in lines])
    return lines, xyz


def read_vector(path):
    vals = []
    for l in open(path):
        l = l.split("#")[0]
        vals += [float(x.replace("D", "E")) for x in l.split()]
    if len(vals) % 3 != 0:
        sys.exit(f"{path}: number of values ({len(vals)}) is not a multiple of 3")
    return np.array(vals).reshape(-1, 3)


def read_cpptraj_evecs(path, mode):
    """Return (average coords, eigenvalue, eigenvector) for the given mode."""
    lines = open(path).read().split("\n")
    n3 = int(lines[1].split()[0])

    def read_block(start):
        vals, i = [], start
        while len(vals) < n3:
            vals += [float(x) for x in lines[i].split()]
            i += 1
        return np.array(vals), i

    avg, i = read_block(2)
    while i < len(lines):
        m = re.match(r"^\s*(\d+)\s+(\S+)\s*$", lines[i])
        if m and int(m.group(1)) == mode:
            vec, _ = read_block(i + 1)
            return avg.reshape(-1, 3), float(m.group(2)), vec.reshape(-1, 3)
        i += 1
    sys.exit(f"mode {mode} not found in {path}")


def kabsch(mobile, target):
    """Rotation R such that R @ (mobile - c_m) best fits (target - c_t)."""
    a = mobile - mobile.mean(0)
    b = target - target.mean(0)
    u, _, vt = np.linalg.svd(b.T @ a)
    d = np.sign(np.linalg.det(u @ vt))
    r = u @ np.diag([1.0, 1.0, d]) @ vt
    rmsd = np.sqrt((((r @ a.T).T - b) ** 2).sum(1).mean())
    return r, rmsd


def write_movie(path, lines, ref, disp, nframes):
    with open(path, "w") as f:
        for k in range(nframes):
            xyz = ref + np.sin(2 * np.pi * k / nframes) * disp
            f.write(f"MODEL {k + 1:8d}\n")
            for l, (x, y, z) in zip(lines, xyz):
                f.write(f"{l[:30]}{x:8.3f}{y:8.3f}{z:8.3f}{l[54:]}\n")
            f.write("ENDMDL\n")
        f.write("END\n")


def write_arrows(path, ref, arrows, a):
    with open(path, "w") as f:
        f.write(f"""# Displacement arrows generated by make_mode_movie.py
# Usage (in VMD, after loading the structure): source {os.path.basename(path)}
# Edit the settings below and source again to redraw.
set arrow_mol    top
set arrow_color  {a.arrow_color}
set arrow_scale  1.0   ;# extra scaling on top of the lengths stored below
set arrow_min    {a.arrow_min}   ;# skip arrows shorter than this (Angstrom, after scaling)
set arrow_radius {a.arrow_radius}
set arrow_head   0.25  ;# fraction of the arrow length used for the cone
set arrow_res    12

# {{start}} {{displacement}} per atom
set arrow_data {{
""")
        for x0, dv in zip(ref, arrows):
            f.write(f"{{{x0[0]:.3f} {x0[1]:.3f} {x0[2]:.3f}}} {{{dv[0]:.3f} {dv[1]:.3f} {dv[2]:.3f}}}\n")
        f.write("""}

graphics $arrow_mol delete all
graphics $arrow_mol color $arrow_color
graphics $arrow_mol materials off
foreach {start dv} $arrow_data {
    set dv [vecscale $arrow_scale $dv]
    set len [veclength $dv]
    if {$len < $arrow_min || $len == 0} continue
    set tip [vecadd $start $dv]
    set mid [vecadd $start [vecscale [expr {1.0 - $arrow_head}] $dv]]
    graphics $arrow_mol cylinder $start $mid radius $arrow_radius resolution $arrow_res filled yes
    graphics $arrow_mol cone $mid $tip radius [expr {2.2 * $arrow_radius}] resolution $arrow_res
}
""")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("pdb", help="reference PDB (atoms in the same order as the vector)")
    p.add_argument("-o", "--prefix", default="mode", help="output prefix (default: mode)")
    g = p.add_argument_group("mode vector")
    g.add_argument("--vector", help="vector file (3N values)")
    g.add_argument("--evecs", help="cpptraj eigenvector file")
    g.add_argument("--mode", type=int, default=1, help="mode index in --evecs (default 1)")
    g.add_argument("--no-fit", action="store_true", help="do not fit the --evecs average onto the PDB")
    g.add_argument("--atom-names", nargs="+", help="use only PDB atoms with these names (e.g. CA)")
    g.add_argument("--normalize", action="store_true", help="scale the vector to unit norm")
    g.add_argument("--flip", action="store_true", help="invert the sign of the vector")
    g = p.add_argument_group("movie")
    g.add_argument("--amp", type=float, help="amplitude A in Angstrom (norm of the displacement for a unit vector)")
    g.add_argument("--nsigma", type=float, default=2.0,
                   help="with --evecs and no --amp: A = nsigma * sqrt(eigenvalue) (default 2)")
    g.add_argument("--nframes", type=int, default=40, help="frames per oscillation period (default 40)")
    g = p.add_argument_group("arrows")
    g.add_argument("--arrow-scale", type=float, default=1.0, help="arrow = arrow-scale * A * v (default 1)")
    g.add_argument("--arrow-min", type=float, default=0.0, help="skip arrows shorter than this, in Angstrom (default 0)")
    g.add_argument("--arrow-radius", type=float, default=0.15, help="cylinder radius (default 0.15)")
    g.add_argument("--arrow-color", default="orange", help="VMD color name or ID (default orange)")
    a = p.parse_args()

    if not a.vector and not a.evecs:
        p.error("give --vector and/or --evecs")

    lines, ref = read_pdb(a.pdb, a.atom_names)
    if len(ref) == 0:
        sys.exit(f"no atoms selected from {a.pdb}")

    eigval = None
    avg = None
    if a.evecs:
        avg, eigval, vec = read_cpptraj_evecs(a.evecs, a.mode)
        print(f"mode {a.mode}: eigenvalue {eigval:.4g}")
    if a.vector:
        vec = read_vector(a.vector)
    if len(vec) != len(ref):
        sys.exit(f"atom count mismatch: PDB {len(ref)} vs vector {len(vec)}")

    if avg is not None and not a.no_fit:
        if len(avg) != len(ref):
            sys.exit(f"atom count mismatch: PDB {len(ref)} vs evecs average {len(avg)}")
        r, rmsd = kabsch(avg, ref)
        vec = (r @ vec.T).T
        print(f"fitted evecs average onto PDB: RMSD {rmsd:.2f} A; vector rotated into PDB frame")

    norm = np.linalg.norm(vec)
    print(f"vector norm {norm:.4g}")
    if a.normalize:
        vec = vec / norm
    if a.flip:
        vec = -vec

    amp = a.amp
    if amp is None:
        if eigval is None:
            sys.exit("give --amp (or --evecs to derive the amplitude from the eigenvalue)")
        if eigval <= 0:
            sys.exit(f"eigenvalue {eigval} is not positive; give --amp")
        amp = a.nsigma * np.sqrt(eigval)
        print(f"amplitude {a.nsigma} * sqrt(eigenvalue) = {amp:.2f} A")

    disp = amp * vec
    d = np.linalg.norm(disp, axis=1)
    print(f"atom displacement at max amplitude: max {d.max():.2f} A, mean {d.mean():.2f} A")

    movie = f"{a.prefix}.pdb"
    write_movie(movie, lines, ref, disp, a.nframes)
    print(f"wrote {a.nframes} frames ({len(ref)} atoms) to {movie}")

    arrows = f"{a.prefix}_arrows.tcl"
    write_arrows(arrows, ref, disp * a.arrow_scale, a)
    n_drawn = int((d * a.arrow_scale >= a.arrow_min).sum())
    print(f"wrote arrows to {arrows} ({n_drawn} of {len(ref)} drawn with arrow_min {a.arrow_min})")


if __name__ == "__main__":
    main()
